config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to
    else
      flash.now[:errors] = @bands.errors.full_messages
      render :show
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to bands_url
    else
      flash.now[:errors] = @bands.errors.full_messages
      render :show
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    render :index
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username / password"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :show
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{h(form_authenticity_token)}\"
    >".html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/edit.html.erb
<form class="" action="<%= band_url(@band.id) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>

  <label for="band-name">Band Name</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" name="" value="SUBMIT">

</form>

<%= button_to "delete", band_url, method: :delete%>

app/views/bands/index.html.erb
<h3>Bands Index</h3>
<%= auth_token %>

<% @bands.each do |band| %>
  <p><%= band.name %></p>
  <%= button_to "Edit", edit_band_url(band.id), method: :get %>
<% end %>

<%= link_to "Add a band", new_band_url %>

app/views/bands/new.html.erb
<form class="" action=" <%= bands_url %>
" method="post">
<%= auth_token %>
  <label for="band-name">Band Name</label>
  <input type="text" name="band[name]" value="">

  <input type="submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>

  </header>
  <body>
    <nav>
      <div class="">
        <% if current_user.nil? %>
          <%= link_to "Login", new_session_url %>
          <%= link_to "Sign Up", new_user_url  %>
        <% else %>
          <%= current_user.email %>
          <%= button_to "Logout", session_url, method: :delete %>
        <% end %>
      </div>
    </nav>
    <h1>Music App</h1>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<form class="" action=" <%= users_url %> " method="post">
  <%= auth_token %>

  <p>
    <label for="new-user-email">Email:</label>
    <input type="text" name="user[email]" value=" ">
  </p>
  <p>
    <label for="new-user-password">Password:</label>
    <input type="password" name="user[password]" value="">
  </p>

  <input type="submit">
</form>

app/views/users/show.html.erb
<h3>Hi <%=  current_user.email  %> </h3>